/* AUTO-GENERATED by tools/gen.js — do not edit by hand. */
var WOOL_LEVELS = [
 {
  "id": 1,
  "name": "Heart",
  "hint": "Tap a yarn ball. Kittens unravel that colour from the top of the picture down.",
  "grid": [
   "..RR..RR..",
   ".RKKRRKKR.",
   "RKWKRRKKKR",
   "RKWKKKKKKR",
   "RRKKKKKKRR",
   ".RRKKKKRR.",
   "..RRKKRR..",
   "...RRRR...",
   "....RR...."
  ],
  "rows": [
   [
    {
     "segs": [
      [
       "W",
       2
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       9
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       8
      ]
     ]
    },
    {
     "segs": [
      [
       "K",
       6
      ]
     ]
    },
    {
     "segs": [
      [
       "K",
       8
      ]
     ]
    }
   ],
   [
    {
     "segs": [
      [
       "R",
       7
      ]
     ]
    },
    {
     "segs": [
      [
       "K",
       8
      ]
     ]
    },
    {
     "segs": [
      [
       "K",
       6
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       8
      ]
     ]
    }
   ]
  ],
  "slots": 5,
  "solution": [
   1,
   2,
   3,
   0,
   4,
   5,
   6,
   7,
   8
  ]
 },
 {
  "id": 2,
  "name": "Apple",
  "hint": "A stitch is loose only once the stitch above it is gone. Lower colours must wait.",
  "grid": [
   ".....N.....",
   ".....NGG...",
   "....N.GGG..",
   "..RRRRRRR..",
   ".RRWRRRRRR.",
   "RRWWRRRRRRM",
   "RRWRRRRRRMM",
   "RRRRRRRRRMM",
   ".RRRRRRRMM.",
   "..RRRRRMM..",
   "...RR.RR..."
  ],
  "rows": [
   [
    {
     "segs": [
      [
       "N",
       3
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       8
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       11
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       6
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       6
      ]
     ]
    }
   ],
   [
    {
     "segs": [
      [
       "R",
       7
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       4
      ]
     ]
    },
    {
     "segs": [
      [
       "M",
       9
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       12
      ]
     ]
    }
   ],
   [
    {
     "segs": [
      [
       "G",
       5
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       6
      ]
     ]
    }
   ]
  ],
  "slots": 5,
  "solution": [
   0,
   1,
   2,
   3,
   4,
   6,
   5,
   7,
   9,
   8,
   10
  ]
 },
 {
  "id": 3,
  "name": "Flower",
  "hint": "A ball with no loose stitches clogs its cushion. Fill every cushion and you are stuck.",
  "grid": [
   "....KKK....",
   "..KKKKKKK..",
   ".KKKYYYKKK.",
   ".KKYYWYYKK.",
   ".KKKYYYKKK.",
   "..KKKKKKK..",
   "....KKK....",
   "...L.G.L...",
   "..LLLGLLL..",
   "....LGL....",
   ".....G.....",
   "...NNNNN..."
  ],
  "rows": [
   [
    {
     "segs": [
      [
       "K",
       8
      ]
     ]
    },
    {
     "segs": [
      [
       "K",
       9
      ]
     ]
    },
    {
     "segs": [
      [
       "N",
       5
      ]
     ]
    },
    {
     "segs": [
      [
       "G",
       4
      ]
     ]
    },
    {
     "segs": [
      [
       "K",
       10
      ]
     ]
    }
   ],
   [
    {
     "segs": [
      [
       "K",
       9
      ]
     ]
    },
    {
     "segs": [
      [
       "L",
       10
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       1
      ]
     ]
    },
    {
     "segs": [
      [
       "Y",
       10
      ]
     ]
    }
   ]
  ],
  "slots": 5,
  "solution": [
   0,
   1,
   2,
   4,
   6,
   3,
   8,
   5,
   7
  ]
 },
 {
  "id": 4,
  "name": "Tabby",
  "hint": "TANGLED yarn! A two-tone ball unravels its first colour, then turns into the second.",
  "grid": [
   ".O........O.",
   ".OK......KO.",
   ".OKO....OKO.",
   ".OODOODOODO.",
   "OODOOOOOODOO",
   "OOOOGOOGOOOO",
   "OOOOOOOOOOOO",
   "OOOWWWWWWOOO",
   "OOWWWKKWWWOO",
   ".OWWWWWWWWO.",
   ".OOOWWWWOOO.",
   "..OOOOOOOO.."
  ],
  "rows": [
   [
    {
     "segs": [
      [
       "W",
       6
      ],
      [
       "O",
       8
      ]
     ]
    },
    {
     "segs": [
      [
       "G",
       2
      ]
     ]
    },
    {
     "segs": [
      [
       "O",
       11
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       7
      ]
     ]
    },
    {
     "segs": [
      [
       "D",
       5
      ]
     ]
    }
   ],
   [
    {
     "segs": [
      [
       "O",
       9
      ]
     ]
    },
    {
     "segs": [
      [
       "O",
       7
      ],
      [
       "W",
       6
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       5
      ]
     ]
    },
    {
     "segs": [
      [
       "O",
       8
      ]
     ]
    }
   ],
   [
    {
     "segs": [
      [
       "O",
       9
      ]
     ]
    },
    {
     "segs": [
      [
       "K",
       6
      ]
     ]
    },
    {
     "segs": [
      [
       "O",
       10
      ]
     ]
    },
    {
     "segs": [
      [
       "O",
       11
      ]
     ]
    }
   ]
  ],
  "slots": 5,
  "solution": [
   2,
   4,
   0,
   1,
   5,
   6,
   9,
   10,
   3,
   8,
   7,
   11,
   12
  ]
 },
 {
  "id": 5,
  "name": "Sheep",
  "hint": "Count what is left before you commit a colour.",
  "grid": [
   "........WWWWWWWWWW........",
   "........WWWWWWWWWW........",
   "....WWWWWWWWWWWWWWWWWW....",
   "....WWWWWWWWWWWWWWWWWW....",
   "..WWWWWWWWWWWWWWWWWWWWWW..",
   "..WWWWWWWWWWWWWWWWWWWWWW..",
   "..WWWWWWWWWWWWWWWWDDDDDD..",
   "..WWWWWWWWWWWWWWWWDDDDDD..",
   "WWWWWWWWWWWWWWWWDDDDDDDDDD",
   "WWWWWWWWWWWWWWWWDDDDDDDDDD",
   "WWWWWWWWWWWWWWWWDDSSDDSSDD",
   "WWWWWWWWWWWWWWWWDDSSDDSSDD",
   "WWWWWWWWWWWWWWWWWWDDDDDDDD",
   "WWWWWWWWWWWWWWWWWWDDDDDDDD",
   "..WWWWWWWWWWWWWWWWDDDDKK..",
   "..WWWWWWWWWWWWWWWWDDDDKK..",
   "..WWWWWWWWWWWWWWWWWWWWWW..",
   "..WWWWWWWWWWWWWWWWWWWWWW..",
   "....DDDD..........DDDD....",
   "....DDDD..........DDDD....",
   "GGGGGGGGGGGGGGGGGGGGGGGGGG",
   "GGGGGGGGGGGGGGGGGGGGGGGGGG"
  ],
  "rows": [
   [
    {
     "segs": [
      [
       "D",
       9
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       10
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       13
      ]
     ]
    },
    {
     "segs": [
      [
       "G",
       12
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       8
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       10
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       9
      ]
     ]
    }
   ],
   [
    {
     "segs": [
      [
       "W",
       15
      ]
     ]
    },
    {
     "segs": [
      [
       "G",
       19
      ]
     ]
    },
    {
     "segs": [
      [
       "D",
       14
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       9
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       8
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       19
      ]
     ]
    }
   ],
   [
    {
     "segs": [
      [
       "G",
       21
      ],
      [
       "W",
       10
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       14
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       20
      ]
     ]
    },
    {
     "segs": [
      [
       "D",
       21
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       15
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       8
      ],
      [
       "D",
       11
      ]
     ]
    },
    {
     "segs": [
      [
       "K",
       4
      ]
     ]
    }
   ],
   [
    {
     "segs": [
      [
       "D",
       10
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       10
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       18
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       22
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       21
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       13
      ]
     ]
    }
   ],
   [
    {
     "segs": [
      [
       "W",
       11
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       16
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       9
      ]
     ]
    },
    {
     "segs": [
      [
       "D",
       19
      ]
     ]
    },
    {
     "segs": [
      [
       "S",
       8
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       20
      ]
     ]
    }
   ]
  ],
  "slots": 5,
  "solution": [
   0,
   1,
   2,
   3,
   4,
   5,
   6,
   7,
   9,
   10,
   11,
   12,
   13,
   8,
   14,
   15,
   16,
   17,
   18,
   20,
   21,
   22,
   23,
   24,
   26,
   27,
   28,
   30,
   19,
   25,
   29,
   31
  ]
 },
 {
  "id": 6,
  "name": "Mushroom",
  "hint": "Deep balls unlock when the balls resting on them are gone.",
  "grid": [
   "........RRRRRRRR........",
   "........RRRRRRRR........",
   "....RRRRWWWWRRRRRRRR....",
   "....RRRRWWWWRRRRRRRR....",
   "..RRRRWWWWWWWWRRRRWWRR..",
   "..RRRRWWWWWWWWRRRRWWRR..",
   "RRRRRRWWWWRRRRRRWWWWWWRR",
   "RRRRRRWWWWRRRRRRWWWWWWRR",
   "RRRRRRRRRRRRRRRRWWWWRRRR",
   "RRRRRRRRRRRRRRRRWWWWRRRR",
   "RRWWWWRRRRRRRRRRRRRRRRRR",
   "RRWWWWRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRR",
   "........EEEEEEEE........",
   "........EEEEEEEE........",
   "........EEEEEEEE........",
   "........EEEEEEEE........",
   "......EEEEEEEEEEEE......",
   "......EEEEEEEEEEEE......",
   "......EEEEEEEEEEEE......",
   "......EEEEEEEEEEEE......",
   "GGGGGGGGEEEEEEEEGGGGGGGG",
   "GGGGGGGGEEEEEEEEGGGGGGGG",
   "GGGGGGGGGGGGGGGGGGGGGGGG",
   "GGGGGGGGGGGGGGGGGGGGGGGG"
  ],
  "rows": [
   [
    {
     "segs": [
      [
       "E",
       8
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       10
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       19
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       9
      ]
     ]
    },
    {
     "segs": [
      [
       "E",
       12
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       16
      ]
     ]
    }
   ],
   [
    {
     "segs": [
      [
       "E",
       18
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       11
      ]
     ]
    },
    {
     "segs": [
      [
       "E",
       19
      ]
     ]
    },
    {
     "segs": [
      [
       "E",
       13
      ],
      [
       "G",
       14
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       15
      ]
     ]
    }
   ],
   [
    {
     "segs": [
      [
       "R",
       18
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       18
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       14
      ],
      [
       "R",
       9
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       10
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       10
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       18
      ]
     ]
    }
   ],
   [
    {
     "segs": [
      [
       "R",
       13
      ]
     ]
    },
    {
     "segs": [
      [
       "G",
       18
      ]
     ]
    },
    {
     "segs": [
      [
       "E",
       10
      ],
      [
       "R",
       20
      ]
     ]
    },
    {
     "segs": [
      [
       "G",
       16
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       11
      ]
     ]
    }
   ],
   [
    {
     "segs": [
      [
       "R",
       12
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       8
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       15
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       16
      ]
     ]
    },
    {
     "segs": [
      [
       "G",
       21
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       8
      ]
     ]
    }
   ],
   [
    {
     "segs": [
      [
       "G",
       11
      ]
     ]
    },
    {
     "segs": [
      [
       "E",
       16
      ]
     ]
    }
   ]
  ],
  "slots": 5,
  "solution": [
   0,
   1,
   2,
   3,
   4,
   5,
   7,
   10,
   16,
   6,
   11,
   12,
   17,
   22,
   8,
   13,
   18,
   23,
   9,
   14,
   15,
   19,
   20,
   24,
   25,
   21,
   26,
   27,
   28,
   29
  ]
 },
 {
  "id": 7,
  "name": "Butterfly",
  "hint": "Keep one cushion free whenever you can.",
  "grid": [
   "..DD..................DD..",
   "..DD..................DD..",
   "....DD..............DD....",
   "....DD..............DD....",
   "..PPPPPP..........PPPPPP..",
   "..PPPPPP..........PPPPPP..",
   "PPPPBBBBPP..DD..PPBBBBPPPP",
   "PPPPBBBBPP..DD..PPBBBBPPPP",
   "PPBBYYBBPPPPDDPPPPBBYYBBPP",
   "PPBBYYBBPPPPDDPPPPBBYYBBPP",
   "PPBBBBBBBBPPDDPPBBBBBBBBPP",
   "PPBBBBBBBBPPDDPPBBBBBBBBPP",
   "..PPPPPPPPPPDDPPPPPPPPPP..",
   "..PPPPPPPPPPDDPPPPPPPPPP..",
   "....KKKKKKPPDDPPKKKKKK....",
   "....KKKKKKPPDDPPKKKKKK....",
   "..KKKKYYKKKKDDKKKKYYKKKK..",
   "..KKKKYYKKKKDDKKKKYYKKKK..",
   "..KKKKKKKKKKDDKKKKKKKKKK..",
   "..KKKKKKKKKKDDKKKKKKKKKK..",
   "....KKKKKK..DD..KKKKKK....",
   "....KKKKKK..DD..KKKKKK...."
  ],
  "rows": [
   [
    {
     "segs": [
      [
       "P",
       8
      ]
     ]
    },
    {
     "segs": [
      [
       "B",
       15
      ]
     ]
    },
    {
     "segs": [
      [
       "K",
       18
      ],
      [
       "P",
       13
      ]
     ]
    },
    {
     "segs": [
      [
       "B",
       18
      ]
     ]
    },
    {
     "segs": [
      [
       "D",
       9
      ]
     ]
    },
    {
     "segs": [
      [
       "P",
       14
      ]
     ]
    }
   ],
   [
    {
     "segs": [
      [
       "P",
       16
      ]
     ]
    },
    {
     "segs": [
      [
       "K",
       11
      ]
     ]
    },
    {
     "segs": [
      [
       "D",
       10
      ],
      [
       "P",
       18
      ]
     ]
    },
    {
     "segs": [
      [
       "P",
       9
      ],
      [
       "B",
       15
      ]
     ]
    },
    {
     "segs": [
      [
       "P",
       11
      ]
     ]
    }
   ],
   [
    {
     "segs": [
      [
       "D",
       16
      ]
     ]
    },
    {
     "segs": [
      [
       "K",
       15
      ]
     ]
    },
    {
     "segs": [
      [
       "Y",
       16
      ]
     ]
    },
    {
     "segs": [
      [
       "P",
       14
      ]
     ]
    },
    {
     "segs": [
      [
       "P",
       15
      ]
     ]
    },
    {
     "segs": [
      [
       "D",
       13
      ]
     ]
    }
   ],
   [
    {
     "segs": [
      [
       "K",
       8
      ]
     ]
    },
    {
     "segs": [
      [
       "K",
       18
      ]
     ]
    },
    {
     "segs": [
      [
       "P",
       18
      ]
     ]
    },
    {
     "segs": [
      [
       "K",
       10
      ]
     ]
    },
    {
     "segs": [
      [
       "K",
       13
      ],
      [
       "B",
       16
      ]
     ]
    }
   ],
   [
    {
     "segs": [
      [
       "K",
       18
      ]
     ]
    },
    {
     "segs": [
      [
       "K",
       9
      ]
     ]
    }
   ]
  ],
  "slots": 5,
  "solution": [
   0,
   2,
   4,
   5,
   1,
   3,
   6,
   8,
   9,
   10,
   11,
   14,
   15,
   7,
   13,
   16,
   20,
   21,
   12,
   19,
   17,
   18,
   22,
   23
  ]
 },
 {
  "id": 8,
  "name": "Rocket",
  "hint": "The Hook booster pulls a ball back out of its cushion.",
  "grid": [
   "............RR............",
   "............RR............",
   "..........RRRRRR..........",
   "..........RRRRRR..........",
   "........RRRRRRRRRR........",
   "........RRRRRRRRRR........",
   "........WWWWWWWWWW........",
   "........WWWWWWWWWW........",
   "......WWWWWWWWWWWWWW......",
   "......WWWWWWWWWWWWWW......",
   "......WWWWBBBBBBWWWW......",
   "......WWWWBBBBBBWWWW......",
   "......WWBBBBSSBBBBWW......",
   "......WWBBBBSSBBBBWW......",
   "......WWWWBBBBBBWWWW......",
   "......WWWWBBBBBBWWWW......",
   "......WWWWWWWWWWWWWW......",
   "......WWWWWWWWWWWWWW......",
   "....RRWWWWWWWWWWWWWWRR....",
   "....RRWWWWWWWWWWWWWWRR....",
   "..RRRRWWWWWWWWWWWWWWRRRR..",
   "..RRRRWWWWWWWWWWWWWWRRRR..",
   "RRRRRRWWWWEEEEEEWWWWRRRRRR",
   "RRRRRRWWWWEEEEEEWWWWRRRRRR",
   "RRRRRR..EEEEEEEEEE..RRRRRR",
   "RRRRRR..EEEEEEEEEE..RRRRRR",
   "........OOOOOOOOOO........",
   "........OOOOOOOOOO........",
   "..........OOYYOO..........",
   "..........OOYYOO..........",
   "............YY............",
   "............YY............"
  ],
  "rows": [
   [
    {
     "segs": [
      [
       "W",
       15
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       10
      ]
     ]
    },
    {
     "segs": [
      [
       "B",
       8
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       11
      ],
      [
       "O",
       12
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       15
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       17
      ]
     ]
    }
   ],
   [
    {
     "segs": [
      [
       "W",
       10
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       14
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       14
      ]
     ]
    },
    {
     "segs": [
      [
       "B",
       8
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       10
      ]
     ]
    }
   ],
   [
    {
     "segs": [
      [
       "S",
       4
      ],
      [
       "W",
       13
      ]
     ]
    },
    {
     "segs": [
      [
       "O",
       16
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       13
      ],
      [
       "B",
       16
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       11
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       12
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       8
      ]
     ]
    }
   ],
   [
    {
     "segs": [
      [
       "B",
       8
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       10
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       11
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       8
      ]
     ]
    },
    {
     "segs": [
      [
       "E",
       11
      ]
     ]
    }
   ],
   [
    {
     "segs": [
      [
       "E",
       8
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       17
      ],
      [
       "Y",
       8
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       18
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       11
      ],
      [
       "R",
       13
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       8
      ]
     ]
    },
    {
     "segs": [
      [
       "E",
       13
      ]
     ]
    }
   ],
   [
    {
     "segs": [
      [
       "W",
       15
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       12
      ]
     ]
    }
   ]
  ],
  "slots": 5,
  "solution": [
   0,
   1,
   3,
   4,
   5,
   6,
   10,
   16,
   2,
   7,
   8,
   13,
   9,
   14,
   11,
   15,
   19,
   20,
   21,
   25,
   26,
   27,
   12,
   17,
   18,
   23,
   24,
   28,
   22,
   29
  ]
 },
 {
  "id": 9,
  "name": "Cottage",
  "hint": "Snip a tangled ball to split its second colour back into the pile.",
  "grid": [
   "............RR............",
   "............RR............",
   "..........RRRRRR....DDDD..",
   "..........RRRRRR....DDDD..",
   "........RRRRRRRRRR..DDDD..",
   "........RRRRRRRRRR..DDDD..",
   "......RRRRRRRRRRRRRRRRRR..",
   "......RRRRRRRRRRRRRRRRRR..",
   "....RRRRRRRRRRRRRRRRRRRRRR",
   "....RRRRRRRRRRRRRRRRRRRRRR",
   "..RRRRRRRRRRRRRRRRRRRRRRRR",
   "..RRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRR",
   "RRRRRRRRRRRRRRRRRRRRRRRRRR",
   "..YYYYYYYYYYYYYYYYYYYYYY..",
   "..YYYYYYYYYYYYYYYYYYYYYY..",
   "..YYBBBBYYYYNNNNYYYYBBBBYY",
   "..YYBBBBYYYYNNNNYYYYBBBBYY",
   "..YYBBBBYYYYNNNNYYYYBBBBYY",
   "..YYBBBBYYYYNNNNYYYYBBBBYY",
   "..YYYYYYYYYYNNNNYYYYYYYYYY",
   "..YYYYYYYYYYNNNNYYYYYYYYYY",
   "..YYYYYYYYYYNNNNYYYYYYYYYY",
   "..YYYYYYYYYYNNNNYYYYYYYYYY",
   "GGGGGGGGGGGGGGGGGGGGGGGGGG",
   "GGGGGGGGGGGGGGGGGGGGGGGGGG"
  ],
  "rows": [
   [
    {
     "segs": [
      [
       "R",
       10
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       16
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       12
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       8
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       18
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       20
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       20
      ],
      [
       "G",
       9
      ]
     ]
    }
   ],
   [
    {
     "segs": [
      [
       "R",
       10
      ]
     ]
    },
    {
     "segs": [
      [
       "Y",
       18
      ]
     ]
    },
    {
     "segs": [
      [
       "Y",
       16
      ]
     ]
    },
    {
     "segs": [
      [
       "Y",
       9
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       14
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       19
      ]
     ]
    }
   ],
   [
    {
     "segs": [
      [
       "Y",
       8
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       13
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       20
      ]
     ]
    },
    {
     "segs": [
      [
       "N",
       13
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       12
      ]
     ]
    },
    {
     "segs": [
      [
       "G",
       13
      ]
     ]
    },
    {
     "segs": [
      [
       "Y",
       15
      ]
     ]
    }
   ],
   [
    {
     "segs": [
      [
       "Y",
       13
      ],
      [
       "N",
       8
      ]
     ]
    },
    {
     "segs": [
      [
       "Y",
       8
      ]
     ]
    },
    {
     "segs": [
      [
       "B",
       14
      ]
     ]
    },
    {
     "segs": [
      [
       "Y",
       13
      ]
     ]
    },
    {
     "segs": [
      [
       "Y",
       10
      ]
     ]
    },
    {
     "segs": [
      [
       "Y",
       18
      ]
     ]
    }
   ],
   [
    {
     "segs": [
      [
       "D",
       16
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       13
      ],
      [
       "G",
       12
      ]
     ]
    },
    {
     "segs": [
      [
       "Y",
       17
      ]
     ]
    },
    {
     "segs": [
      [
       "B",
       18
      ]
     ]
    },
    {
     "segs": [
      [
       "Y",
       16
      ]
     ]
    },
    {
     "segs": [
      [
       "N",
       11
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       11
      ]
     ]
    }
   ],
   [
    {
     "segs": [
      [
       "Y",
       11
      ]
     ]
    },
    {
     "segs": [
      [
       "G",
       18
      ]
     ]
    }
   ]
  ],
  "slots": 5,
  "solution": [
   0,
   1,
   2,
   3,
   4,
   5,
   6,
   7,
   8,
   11,
   12,
   14,
   9,
   15,
   10,
   13,
   16,
   17,
   19,
   20,
   21,
   22,
   23,
   26,
   27,
   28,
   29,
   33,
   18,
   24,
   25,
   31,
   32,
   30,
   34
  ]
 },
 {
  "id": 10,
  "name": "Sundae",
  "hint": "Final level. Every band waits on the band above it. Plan the whole pile before you tap.",
  "grid": [
   "..........RR..........",
   "..........RR..........",
   "......KKKKKKKKKK......",
   "......KKKKKKKKKK......",
   "....KKKKKKKKKKKKKK....",
   "....KKKKKKKKKKKKKK....",
   "....KKKKKKKKKKKKKK....",
   "....KKKKKKKKKKKKKK....",
   "..WWWWWWWWWWWWWWWWWW..",
   "..WWWWWWWWWWWWWWWWWW..",
   "..WWWWWWWWWWWWWWWWWW..",
   "..WWWWWWWWWWWWWWWWWW..",
   "..NNNNNNNNNNNNNNNNNN..",
   "..NNNNNNNNNNNNNNNNNN..",
   "NNNNNNNNNNNNNNNNNNNNNN",
   "NNNNNNNNNNNNNNNNNNNNNN",
   "..NNNNNNNNNNNNNNNNNN..",
   "..NNNNNNNNNNNNNNNNNN..",
   "..YYYYYYYYYYYYYYYYYY..",
   "..YYYYYYYYYYYYYYYYYY..",
   "....YYYYNNYYYYNNYYYY..",
   "....YYYYNNYYYYNNYYYY..",
   "....YYYYYYYYYYYYYY....",
   "....YYYYYYYYYYYYYY....",
   "......YYNNYYNNYY......",
   "......YYNNYYNNYY......",
   "........YYYYYY........",
   "........YYYYYY........",
   "..........YY..........",
   "..........YY.........."
  ],
  "rows": [
   [
    {
     "segs": [
      [
       "W",
       13
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       10
      ]
     ]
    },
    {
     "segs": [
      [
       "N",
       16
      ],
      [
       "K",
       14
      ]
     ]
    },
    {
     "segs": [
      [
       "N",
       14
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       13
      ]
     ]
    },
    {
     "segs": [
      [
       "K",
       12
      ]
     ]
    }
   ],
   [
    {
     "segs": [
      [
       "K",
       8
      ]
     ]
    },
    {
     "segs": [
      [
       "N",
       17
      ]
     ]
    },
    {
     "segs": [
      [
       "Y",
       11
      ]
     ]
    },
    {
     "segs": [
      [
       "Y",
       16
      ],
      [
       "W",
       9
      ]
     ]
    },
    {
     "segs": [
      [
       "K",
       19
      ]
     ]
    }
   ],
   [
    {
     "segs": [
      [
       "K",
       11
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       8
      ]
     ]
    },
    {
     "segs": [
      [
       "Y",
       19
      ]
     ]
    },
    {
     "segs": [
      [
       "N",
       11
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       11
      ],
      [
       "N",
       11
      ]
     ]
    },
    {
     "segs": [
      [
       "R",
       4
      ]
     ]
    }
   ],
   [
    {
     "segs": [
      [
       "Y",
       9
      ]
     ]
    },
    {
     "segs": [
      [
       "N",
       11
      ]
     ]
    },
    {
     "segs": [
      [
       "Y",
       15
      ]
     ]
    },
    {
     "segs": [
      [
       "W",
       8
      ]
     ]
    },
    {
     "segs": [
      [
       "Y",
       19
      ]
     ]
    }
   ],
   [
    {
     "segs": [
      [
       "N",
       19
      ]
     ]
    },
    {
     "segs": [
      [
       "K",
       12
      ]
     ]
    },
    {
     "segs": [
      [
       "Y",
       17
      ]
     ]
    },
    {
     "segs": [
      [
       "N",
       17
      ]
     ]
    },
    {
     "segs": [
      [
       "Y",
       10
      ]
     ]
    },
    {
     "segs": [
      [
       "N",
       16
      ]
     ]
    }
   ]
  ],
  "slots": 5,
  "solution": [
   0,
   1,
   2,
   3,
   5,
   6,
   7,
   8,
   11,
   13,
   4,
   10,
   12,
   16,
   9,
   15,
   14,
   20,
   18,
   17,
   22,
   19,
   23,
   25,
   21,
   24,
   27,
   26
  ]
 }
];
if (typeof module === "object" && module.exports) module.exports = WOOL_LEVELS;
