/* Hand-drawn knit pictures for the 10 launch levels.
 * Letters map to WoolEngine.PALETTE; '.' is an empty cell.
 * Each entry also carries the generator settings used to build its yarn pile.
 */
module.exports = [
  {
    id: 1, name: 'Heart', hint: 'Tap a yarn ball. Kittens unravel that colour from the top of the picture down.',
    chunk: [6, 12], tangled: 0, target: [0.85, 1.0], naiveMustFail: false, seed: 1, scale: 1,
    grid: [
      '..RR..RR..',
      '.RKKRRKKR.',
      'RKWKRRKKKR',
      'RKWKKKKKKR',
      'RRKKKKKKRR',
      '.RRKKKKRR.',
      '..RRKKRR..',
      '...RRRR...',
      '....RR....',
    ],
  },
  {
    id: 2, name: 'Apple', hint: 'A stitch is loose only once the stitch above it is gone. Lower colours must wait.',
    chunk: [6, 12], tangled: 0, target: [0.5, 0.95], naiveMustFail: false, seed: 1, scale: 1,
    grid: [
      '.....N.....',
      '.....NGG...',
      '....N.GGG..',
      '..RRRRRRR..',
      '.RRWRRRRRR.',
      'RRWWRRRRRRM',
      'RRWRRRRRRMM',
      'RRRRRRRRRMM',
      '.RRRRRRRMM.',
      '..RRRRRMM..',
      '...RR.RR...',
    ],
  },
  {
    id: 3, name: 'Flower', hint: 'A ball with no loose stitches clogs its cushion. Fill every cushion and you are stuck.',
    chunk: [5, 11], tangled: 0, target: [0.35, 0.8], naiveMustFail: true, seed: 1, scale: 1,
    grid: [
      '....KKK....',
      '..KKKKKKK..',
      '.KKKYYYKKK.',
      '.KKYYWYYKK.',
      '.KKKYYYKKK.',
      '..KKKKKKK..',
      '....KKK....',
      '...L.G.L...',
      '..LLLGLLL..',
      '....LGL....',
      '.....G.....',
      '...NNNNN...',
    ],
  },
  {
    id: 4, name: 'Tabby', hint: 'TANGLED yarn! A two-tone ball unravels its first colour, then turns into the second.',
    chunk: [5, 11], tangled: 2, target: [0.3, 0.7], naiveMustFail: true, seed: 1, scale: 1,
    grid: [
      '.O........O.',
      '.OK......KO.',
      '.OKO....OKO.',
      '.OODOODOODO.',
      'OODOOOOOODOO',
      'OOOOGOOGOOOO',
      'OOOOOOOOOOOO',
      'OOOWWWWWWOOO',
      'OOWWWKKWWWOO',
      '.OWWWWWWWWO.',
      '.OOOWWWWOOO.',
      '..OOOOOOOO..',
    ],
  },
  {
    id: 5, name: 'Sheep', hint: 'Count what is left before you commit a colour.',
    chunk: [8, 22], tangled: 2, target: [0.25, 0.6], naiveMustFail: true, seed: 1, scale: 2,
    grid: [
      '....WWWWW....',
      '..WWWWWWWWW..',
      '.WWWWWWWWWWW.',
      '.WWWWWWWWDDD.',
      'WWWWWWWWDDDDD',
      'WWWWWWWWDSDSD',
      'WWWWWWWWWDDDD',
      '.WWWWWWWWDDK.',
      '.WWWWWWWWWWW.',
      '..DD.....DD..',
      'GGGGGGGGGGGGG',
    ],
  },
  {
    id: 6, name: 'Mushroom', hint: 'Deep balls unlock when the balls resting on them are gone.',
    chunk: [8, 22], tangled: 3, target: [0.2, 0.5], naiveMustFail: true, seed: 1, scale: 2,
    grid: [
      '....RRRR....',
      '..RRWWRRRR..',
      '.RRWWWWRRWR.',
      'RRRWWRRRWWWR',
      'RRRRRRRRWWRR',
      'RWWRRRRRRRRR',
      'RRRRRRRRRRRR',
      '....EEEE....',
      '....EEEE....',
      '...EEEEEE...',
      '...EEEEEE...',
      'GGGGEEEEGGGG',
      'GGGGGGGGGGGG',
    ],
  },
  {
    id: 7, name: 'Butterfly', hint: 'Keep one cushion free whenever you can.',
    chunk: [8, 18], tangled: 4, target: [0.15, 0.4], naiveMustFail: true, seed: 1, scale: 2,
    grid: [
      '.D.........D.',
      '..D.......D..',
      '.PPP.....PPP.',
      'PPBBP.D.PBBPP',
      'PBYBPPDPPBYBP',
      'PBBBBPDPBBBBP',
      '.PPPPPDPPPPP.',
      '..KKKPDPKKK..',
      '.KKYKKDKKYKK.',
      '.KKKKKDKKKKK.',
      '..KKK.D.KKK..',
    ],
  },
  {
    id: 8, name: 'Rocket', hint: 'The Hook booster pulls a ball back out of its cushion.',
    chunk: [8, 18], tangled: 5, target: [0.1, 0.3], naiveMustFail: true, seed: 1, scale: 2,
    grid: [
      '......R......',
      '.....RRR.....',
      '....RRRRR....',
      '....WWWWW....',
      '...WWWWWWW...',
      '...WWBBBWW...',
      '...WBBSBBW...',
      '...WWBBBWW...',
      '...WWWWWWW...',
      '..RWWWWWWWR..',
      '.RRWWWWWWWRR.',
      'RRRWWEEEWWRRR',
      'RRR.EEEEE.RRR',
      '....OOOOO....',
      '.....OYO.....',
      '......Y......',
    ],
  },
  {
    id: 9, name: 'Cottage', hint: 'Snip a tangled ball to split its second colour back into the pile.',
    chunk: [8, 20], tangled: 3, target: [0.06, 0.2], naiveMustFail: true, seed: 1, scale: 2,
    grid: [
      '......R......',
      '.....RRR..DD.',
      '....RRRRR.DD.',
      '...RRRRRRRRR.',
      '..RRRRRRRRRRR',
      '.RRRRRRRRRRRR',
      'RRRRRRRRRRRRR',
      '.YYYYYYYYYYY.',
      '.YBBYYNNYYBBY',
      '.YBBYYNNYYBBY',
      '.YYYYYNNYYYYY',
      '.YYYYYNNYYYYY',
      'GGGGGGGGGGGGG',
    ],
  },
  {
    id: 10, name: 'Sundae', hint: 'Final level. Every band waits on the band above it. Plan the whole pile before you tap.',
    chunk: [8, 20], tangled: 3, target: [0.02, 0.12], naiveMustFail: true, seed: 1, scale: 2,
    grid: [
      '.....R.....',
      '...KKKKK...',
      '..KKKKKKK..',
      '..KKKKKKK..',
      '.WWWWWWWWW.',
      '.WWWWWWWWW.',
      '.NNNNNNNNN.',
      'NNNNNNNNNNN',
      '.NNNNNNNNN.',
      '.YYYYYYYYY.',
      '..YYNYYNYY.',
      '..YYYYYYY..',
      '...YNYNY...',
      '....YYY....',
      '.....Y.....',
    ],
  },
];
